import './globals.css'
import { Roboto_Slab } from 'next/font/google'

export const robotoSlab = Roboto_Slab({ subsets: ['latin'] })

export const metadata = {
  title: 'Sites de Alta Perfomance!',
  description: 'Generated by create next app',

}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body className={robotoSlab.className}>{children}</body>
    </html>
  )
}
